workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

stages:
  - release
# sast:
#   stage: test
# include:
#   - template: Auto-DevOps.gitlab-ci.yml

publish:
  image: node:22
  stage: release
  script:
    - npm cache clean --force
    - rm -rf node_modules package-lock.json || true
    - npm install
    - |
      cat > .npmrc <<EOF
      @${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/
      ${CI_API_V4_URL#http?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}
      EOF
    - npm run semantic-release
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
