// Captured from the pinned integration database; see source and image below.
export const oracleRecordMetadataFixture = {
  databaseVersion: '23.26.0.0.0',
  image:
    'gvenzl/oracle-free:23.26.0-slim-faststart@sha256:67de722693c8351cf93a602667926820376c10b3d23e283a6cdcdc50be46ec10',
  nodeOracledbVersion: '7.0.0',
  source:
    'OracleSqlCommand.SQL_GET_PACKAGE_INFO for test/integration/oracle.integration.test.ts package specification',
  rows: [
    {
      procedure_name: 'TRANSFORM_RECORD',
      argument_name: 'P_INPUT',
      order: 1,
      argument_type: 'PL/SQL RECORD',
      mode: 'IN',
      size: null,
      owner: 'TYPEORM',
      subprogram_id: 3,
      overload: null,
      data_level: 0,
      sequence: 1,
      type_owner: 'TYPEORM',
      type_name: 'TPK_IT_PKG',
      type_subname: 'SHIP_RECORD',
      plsql_typecode: 'PL/SQL RECORD',
    },
    {
      procedure_name: 'TRANSFORM_RECORD',
      argument_name: 'SHIP_NAME',
      order: 1,
      argument_type: 'VARCHAR2',
      mode: 'IN',
      size: 40,
      owner: 'TYPEORM',
      subprogram_id: 3,
      overload: null,
      data_level: 1,
      sequence: 1,
      type_owner: null,
      type_name: null,
      type_subname: null,
      plsql_typecode: null,
    },
    {
      procedure_name: 'TRANSFORM_RECORD',
      argument_name: 'WEIGHT',
      order: 1,
      argument_type: 'NUMBER',
      mode: 'IN',
      size: null,
      owner: 'TYPEORM',
      subprogram_id: 3,
      overload: null,
      data_level: 1,
      sequence: 2,
      type_owner: null,
      type_name: null,
      type_subname: null,
      plsql_typecode: null,
    },
    {
      procedure_name: 'TRANSFORM_RECORD',
      argument_name: 'SAILED_AT',
      order: 1,
      argument_type: 'TIMESTAMP WITH TZ',
      mode: 'IN',
      size: null,
      owner: 'TYPEORM',
      subprogram_id: 3,
      overload: null,
      data_level: 1,
      sequence: 3,
      type_owner: null,
      type_name: null,
      type_subname: null,
      plsql_typecode: null,
    },
    {
      procedure_name: 'TRANSFORM_RECORD',
      argument_name: 'TOKEN',
      order: 1,
      argument_type: 'RAW',
      mode: 'IN',
      size: 4,
      owner: 'TYPEORM',
      subprogram_id: 3,
      overload: null,
      data_level: 1,
      sequence: 4,
      type_owner: null,
      type_name: null,
      type_subname: null,
      plsql_typecode: null,
    },
    {
      procedure_name: 'TRANSFORM_RECORD',
      argument_name: 'P_IN_OUT',
      order: 2,
      argument_type: 'PL/SQL RECORD',
      mode: 'IN/OUT',
      size: null,
      owner: 'TYPEORM',
      subprogram_id: 3,
      overload: null,
      data_level: 0,
      sequence: 2,
      type_owner: 'TYPEORM',
      type_name: 'TPK_IT_PKG',
      type_subname: 'SHIP_RECORD',
      plsql_typecode: 'PL/SQL RECORD',
    },
    {
      procedure_name: 'TRANSFORM_RECORD',
      argument_name: 'SHIP_NAME',
      order: 2,
      argument_type: 'VARCHAR2',
      mode: 'IN/OUT',
      size: 40,
      owner: 'TYPEORM',
      subprogram_id: 3,
      overload: null,
      data_level: 1,
      sequence: 1,
      type_owner: null,
      type_name: null,
      type_subname: null,
      plsql_typecode: null,
    },
    {
      procedure_name: 'TRANSFORM_RECORD',
      argument_name: 'WEIGHT',
      order: 2,
      argument_type: 'NUMBER',
      mode: 'IN/OUT',
      size: null,
      owner: 'TYPEORM',
      subprogram_id: 3,
      overload: null,
      data_level: 1,
      sequence: 2,
      type_owner: null,
      type_name: null,
      type_subname: null,
      plsql_typecode: null,
    },
    {
      procedure_name: 'TRANSFORM_RECORD',
      argument_name: 'SAILED_AT',
      order: 2,
      argument_type: 'TIMESTAMP WITH TZ',
      mode: 'IN/OUT',
      size: null,
      owner: 'TYPEORM',
      subprogram_id: 3,
      overload: null,
      data_level: 1,
      sequence: 3,
      type_owner: null,
      type_name: null,
      type_subname: null,
      plsql_typecode: null,
    },
    {
      procedure_name: 'TRANSFORM_RECORD',
      argument_name: 'TOKEN',
      order: 2,
      argument_type: 'RAW',
      mode: 'IN/OUT',
      size: 4,
      owner: 'TYPEORM',
      subprogram_id: 3,
      overload: null,
      data_level: 1,
      sequence: 4,
      type_owner: null,
      type_name: null,
      type_subname: null,
      plsql_typecode: null,
    },
    {
      procedure_name: 'TRANSFORM_RECORD',
      argument_name: 'P_OUTPUT',
      order: 3,
      argument_type: 'PL/SQL RECORD',
      mode: 'OUT',
      size: null,
      owner: 'TYPEORM',
      subprogram_id: 3,
      overload: null,
      data_level: 0,
      sequence: 3,
      type_owner: 'TYPEORM',
      type_name: 'TPK_IT_PKG',
      type_subname: 'SHIP_RECORD',
      plsql_typecode: 'PL/SQL RECORD',
    },
    {
      procedure_name: 'TRANSFORM_RECORD',
      argument_name: 'SHIP_NAME',
      order: 3,
      argument_type: 'VARCHAR2',
      mode: 'OUT',
      size: 40,
      owner: 'TYPEORM',
      subprogram_id: 3,
      overload: null,
      data_level: 1,
      sequence: 1,
      type_owner: null,
      type_name: null,
      type_subname: null,
      plsql_typecode: null,
    },
    {
      procedure_name: 'TRANSFORM_RECORD',
      argument_name: 'WEIGHT',
      order: 3,
      argument_type: 'NUMBER',
      mode: 'OUT',
      size: null,
      owner: 'TYPEORM',
      subprogram_id: 3,
      overload: null,
      data_level: 1,
      sequence: 2,
      type_owner: null,
      type_name: null,
      type_subname: null,
      plsql_typecode: null,
    },
    {
      procedure_name: 'TRANSFORM_RECORD',
      argument_name: 'SAILED_AT',
      order: 3,
      argument_type: 'TIMESTAMP WITH TZ',
      mode: 'OUT',
      size: null,
      owner: 'TYPEORM',
      subprogram_id: 3,
      overload: null,
      data_level: 1,
      sequence: 3,
      type_owner: null,
      type_name: null,
      type_subname: null,
      plsql_typecode: null,
    },
    {
      procedure_name: 'TRANSFORM_RECORD',
      argument_name: 'TOKEN',
      order: 3,
      argument_type: 'RAW',
      mode: 'OUT',
      size: 4,
      owner: 'TYPEORM',
      subprogram_id: 3,
      overload: null,
      data_level: 1,
      sequence: 4,
      type_owner: null,
      type_name: null,
      type_subname: null,
      plsql_typecode: null,
    },
  ],
};
