import type { TIdentifierQuoting } from '../typeorm/data-source/DataSourceOptions.js';
import type { OracleConnectionOptions } from '../typeorm/driver/oracle/OracleConnectionOptions.js';
import type { PostgresConnectionOptions } from '../typeorm/driver/postgres/PostgresConnectionOptions.js';
import type { TAdapterUtilsClassTypes } from '../types/adapter.types.js';
import type { TConnectionMode } from '../types/config.types.js';
import type { TKeyTransformCase } from '../types/strategy.types.js';

export interface IDatabaseCredentials {
  host: string;
  port: number;
  username: string;
  password: string;
  database: string;
}

export interface IResourceLimits {
  /** Maximum rows materialized across all cursors returned by one call. */
  maxProcedureRows: number;
  /** Approximate maximum bytes materialized by one procedure call. */
  maxProcedureBytes: number;
  /** Maximum rows accepted from one procedure metadata query. */
  maxMetadataRows: number;
  /** Maximum bytes read from one CLOB or BLOB output value. */
  maxLobBytes: number;
  /** Maximum number of pending notification events per subscription. */
  maxNotificationQueue: number;
  /** Maximum number of distinct Oracle CQN ROWIDs processed per event. */
  maxNotificationRows: number;
}

export interface IPackagesSettingsDefault {
  /**
   * Database package/schema names to inspect for callable procedures.
   * Keep values lowercase because procedure resolution normalizes names.
   */
  packages: Array<Lowercase<string>>;
  /**
   * Procedures that should be loaded from database metadata.
   * Keys are application labels for this configuration object only; `call()`
   * resolves procedure names from the values, using `package.procedure` or
   * `procedure` when only one package is configured.
   */
  procedureObjectList: Record<string, string>;
  /**
   * Trusted developer SQL used to load procedure argument metadata. Do not
   * build this value from user input.
   * The SQL must contain `:PACKAGE_NAME` and return columns compatible with
   * `IProcedureArgumentBase` after snake_case to camelCase conversion:
   * `procedure_name`, `argument_name`, `argument_type`, `order`, and `mode`.
   * Overloaded routines should also return database-specific identity columns:
   * PostgreSQL `specific_name`, or Oracle `owner`, `subprogram_id`, and
   * `overload`. The library rejects results above `maxMetadataRows`; custom SQL
   * should also apply a database-side limit when its source can be unbounded.
   */
  procedureMetadataSql?: string;
  /**
   * Trusted developer SQL used to subscribe to package metadata change
   * notifications. Do not build this value from user input. PostgreSQL expects
   * a full `LISTEN ...` command. Oracle expects a full CQN `SELECT ...` query.
   */
  metadataNotificationSql?: string;
  /**
   * Enables dynamic package update mode.
   */
  isNeedDynamicallyUpdatePackagesInfo?: boolean;
}

export interface IBaseConfig {
  /** Primary database credentials used for writes and default connections. */
  master: IDatabaseCredentials;
  /** Maximum connection pool size passed to the underlying DataSource. */
  poolSize: number;
  /** Controls quoting of physical identifiers generated by TypeORM. */
  identifierQuoting?: TIdentifierQuoting;
  /** Optional read replicas used by TypeORM replication. */
  slaves?: Array<IDatabaseCredentials>;
  /** Application name sent to the database driver when supported. */
  appName?: string;
  /** Database session time zone passed to the underlying driver. */
  sessionTimeZone?: string;
  /** Slow-query threshold passed to TypeORM. */
  maxQueryExecutionTime?: number;
  /** Global query timeout in milliseconds for library-managed SQL. */
  queryTimeoutMs?: number;
  /** Resource limits for materialized procedure and notification data. */
  resourceLimits?: Partial<IResourceLimits>;
  /** Enables registration of built-in temporal serializers. */
  isNeedRegisterDefaultSerializers?: boolean;
  /** Output key casing for ORM column names and native query result keys. */
  outKeyTransformCase?: TKeyTransformCase;
}

export interface IOracleBaseConfig extends IBaseConfig {
  type: 'oracle';
  packagesSettings?: IPackagesSettingsDefault;
  libraryPath?: string | undefined;
}

export interface IPostgresDbConfig extends IBaseConfig {
  type: 'postgres';
  /** Passed to the bundled Postgres driver as `parseInt8`. */
  parseInt8AsNumber: boolean;
  packagesSettings?: IPackagesSettingsDefault & {
    listenEventName?: string;
  };
}

export interface IEntityOptions {
  isNeedEntitySync: boolean;
  entityPath: Array<string>;
}

export interface IMigrationOptions {
  isNeedMigrationStart: boolean;
  migrationPath: Array<string>;
}

export interface IExecutionOptions {
  /** Connection pool mode used to create an EntityManager. */
  mode?: TConnectionMode;
  /** Restricted setup commands executed before the main query. */
  optionsCommands?: Array<string>;
  /** Optional query id used by logs and database error wrapping. */
  queryId?: string;
}

export interface IDatabaseFactory {
  additionalConfig: PostgresConnectionOptions | OracleConnectionOptions;
  databaseAdapter: TAdapterUtilsClassTypes;
}
