import type { EntityTarget } from '../common/EntityTarget.js';
import type { ObjectLiteral } from '../common/ObjectLiteral.js';
import { DataSource } from '../data-source/DataSource.js';
import { ReturningStatementNotSupportedError } from '../error/ReturningStatementNotSupportedError.js';
import type { QueryRunner } from '../query-runner/QueryRunner.js';
import { InstanceChecker } from '../util/InstanceChecker.js';

import { Brackets } from './Brackets.js';
import { QueryBuilder } from './QueryBuilder.js';
import { DeleteResult } from './result/DeleteResult.js';
import type { WhereExpressionBuilder } from './WhereExpressionBuilder.js';

/**
 * Allows to build complex sql queries in a fashion way and execute those queries.
 */
export class DeleteQueryBuilder<Entity extends ObjectLiteral>
  extends QueryBuilder<Entity>
  implements WhereExpressionBuilder
{
  public readonly '@instanceof' = Symbol.for('DeleteQueryBuilder');

  // -------------------------------------------------------------------------
  // Constructor
  // -------------------------------------------------------------------------

  public constructor(
    connectionOrQueryBuilder: DataSource | QueryBuilder<Entity>,
    queryRunner?: QueryRunner
  ) {
    super(connectionOrQueryBuilder as unknown as DataSource, queryRunner);
    this.expressionMap.aliasNamePrefixingEnabled = false;
  }

  // -------------------------------------------------------------------------
  // Public Implemented Methods
  // -------------------------------------------------------------------------

  /**
   * Gets generated SQL query without parameters being replaced.
   */
  public getQuery(): string {
    let sql = this.createComment();
    sql += this.createCteExpression();
    sql += this.createDeleteExpression();
    return this.replacePropertyNamesForTheWholeQuery(sql.trim());
  }

  /**
   * Executes sql generated by query builder and returns raw database results.
   */
  public async execute(): Promise<DeleteResult> {
    const [sql, parameters] = this.getQueryAndParameters();
    const queryRunner = this.obtainQueryRunner();
    let transactionStartedByUs = false;

    try {
      // start transaction if it was enabled
      if (
        this.expressionMap.useTransaction === true &&
        queryRunner.isTransactionActive === false
      ) {
        await queryRunner.startTransaction();
        transactionStartedByUs = true;
      }

      // call before deletion methods in listeners and subscribers
      if (
        this.expressionMap.callListeners === true &&
        this.expressionMap.mainAlias!.hasMetadata
      ) {
        await queryRunner.broadcaster.broadcast(
          'BeforeRemove',
          this.expressionMap.mainAlias!.metadata
        );
      }

      // execute query
      const queryResult = await queryRunner.query(sql, parameters, true);
      const deleteResult = DeleteResult.from(queryResult);

      // call after deletion methods in listeners and subscribers
      if (
        this.expressionMap.callListeners === true &&
        this.expressionMap.mainAlias!.hasMetadata
      ) {
        await queryRunner.broadcaster.broadcast(
          'AfterRemove',
          this.expressionMap.mainAlias!.metadata
        );
      }

      // close transaction if we started it
      if (transactionStartedByUs) await queryRunner.commitTransaction();

      return deleteResult;
    } catch (error) {
      // rollback transaction if we started it
      if (transactionStartedByUs) {
        try {
          await queryRunner.rollbackTransaction();
        } catch {
          // empty.
        }
      }
      throw error;
    } finally {
      if (queryRunner !== this.queryRunner) {
        // means we created our own query runner
        await queryRunner.release();
      }
    }
  }

  // -------------------------------------------------------------------------
  // Public Methods
  // -------------------------------------------------------------------------

  /**
   * Specifies FROM which entity's table select/update/delete will be executed.
   * Also sets a main string alias of the selection data.
   */
  public from<T extends ObjectLiteral>(
    entityTarget: EntityTarget<T>,
    aliasName?: string
  ): DeleteQueryBuilder<T> {
    entityTarget = InstanceChecker.isEntitySchema(entityTarget)
      ? entityTarget.options.name
      : entityTarget;
    const mainAlias = this.createFromAlias(entityTarget, aliasName);
    this.expressionMap.setMainAlias(mainAlias);
    return this as unknown as DeleteQueryBuilder<T>;
  }

  /**
   * Sets WHERE condition in the query builder.
   * If you had previously WHERE expression defined,
   * calling this function will override previously set WHERE conditions.
   * Additionally you can add parameters used in where expression.
   */
  public where(
    where:
      | Brackets
      | string
      | ((qb: this) => string)
      | ObjectLiteral
      | Array<ObjectLiteral>,
    parameters?: ObjectLiteral
  ): this {
    this.expressionMap.wheres = []; // don't move this block below since computeWhereParameter can add where expressions
    const condition = this.getWhereCondition(where);
    if (condition)
      this.expressionMap.wheres = [{ type: 'simple', condition: condition }];
    if (parameters) this.setParameters(parameters);
    return this;
  }

  /**
   * Adds new AND WHERE condition in the query builder.
   * Additionally you can add parameters used in where expression.
   */
  public andWhere(
    where:
      | Brackets
      | string
      | ((qb: this) => string)
      | ObjectLiteral
      | Array<ObjectLiteral>,
    parameters?: ObjectLiteral
  ): this {
    this.expressionMap.wheres.push({
      type: 'and',
      condition: this.getWhereCondition(where),
    });
    if (parameters) this.setParameters(parameters);
    return this;
  }

  /**
   * Adds new OR WHERE condition in the query builder.
   * Additionally you can add parameters used in where expression.
   */
  public orWhere(
    where:
      | Brackets
      | string
      | ((qb: this) => string)
      | ObjectLiteral
      | Array<ObjectLiteral>,
    parameters?: ObjectLiteral
  ): this {
    this.expressionMap.wheres.push({
      type: 'or',
      condition: this.getWhereCondition(where),
    });
    if (parameters) this.setParameters(parameters);
    return this;
  }

  /**
   * Sets WHERE condition in the query builder with a condition for the given ids.
   * If you had previously WHERE expression defined,
   * calling this function will override previously set WHERE conditions.
   */
  public whereInIds(ids: unknown | Array<unknown>): this {
    return this.where(this.getWhereInIdsCondition(ids));
  }

  /**
   * Adds new AND WHERE with conditions for the given ids.
   */
  public andWhereInIds(ids: unknown | Array<unknown>): this {
    return this.andWhere(this.getWhereInIdsCondition(ids));
  }

  /**
   * Adds new OR WHERE with conditions for the given ids.
   */
  public orWhereInIds(ids: unknown | Array<unknown>): this {
    return this.orWhere(this.getWhereInIdsCondition(ids));
  }
  /**
   * Optional returning/output clause.
   * This will return given column values.
   */
  public output(columns: Array<string>): this;

  /**
   * Optional returning/output clause.
   * Returning is a SQL string containing returning statement.
   */
  public output(output: string): this;

  /**
   * Optional returning/output clause.
   */
  public output(output: string | Array<string>): this;

  /**
   * Optional returning/output clause.
   */
  public output(output: string | Array<string>): this {
    return this.returning(output);
  }

  /**
   * Optional returning/output clause.
   * This will return given column values.
   */
  public returning(columns: Array<string>): this;

  /**
   * Optional returning/output clause.
   * Returning is a SQL string containing returning statement.
   */
  public returning(returning: string): this;

  /**
   * Optional returning/output clause.
   */
  public returning(returning: string | Array<string>): this;

  /**
   * Optional returning/output clause.
   */
  public returning(returning: string | Array<string>): this {
    // not all databases support returning/output cause
    if (!this.driver.isReturningSqlSupported('delete')) {
      throw new ReturningStatementNotSupportedError();
    }

    this.expressionMap.returning = returning;
    return this;
  }

  // -------------------------------------------------------------------------
  // Protected Methods
  // -------------------------------------------------------------------------

  /**
   * Creates DELETE express used to perform query.
   */
  protected createDeleteExpression(): string {
    const tableName = this.getTableName(this.getMainTableName());
    const whereExpression = this.createWhereExpression();
    const returningExpression = this.createReturningExpression('delete');

    if (returningExpression === '') {
      return `DELETE FROM ${tableName}${whereExpression}`;
    }
    // mssql and spanner are not supported in this kit
    // if (this.driver.options.type === 'mssql') {
    //   return `DELETE FROM ${tableName} OUTPUT ${returningExpression}${whereExpression}`;
    // }
    // if (this.driver.options.type === 'spanner') {
    //   return `DELETE FROM ${tableName}${whereExpression} THEN RETURN ${returningExpression}`;
    // }
    return `DELETE FROM ${tableName}${whereExpression} RETURNING ${returningExpression}`;
  }
}
